[workspace]
name = "mvesuvio"
channels = ["conda-forge", "mantid/label/nightly"]
platforms = ["linux-64",
             "win-64",
             { platform = "osx-arm64", macos = "14.0" }]
description = "Analyse Vesuvio instrument data"

[dependencies]
python = ">=3.10"
pip = ">=24.0"
setuptools = ">=71.0.0"
wheel = "*"

[feature.mvesuvio.dependencies]
iminuit = "*"
jacobi = "*"
dill = "*"
mantidworkbench = "*"

[feature.conda-builder.dependencies]
mamba = "*"
conda-build = "*"
boa = "*"
anaconda-client = "*"
conda-verify = "*"

[feature.pypi-builder.dependencies]
python-build = "*"
twine = "*"

[feature.developer.dependencies]
ruff = "*"
pre-commit = "*"
coverage = "*"
mock = "*"
coveralls = "*"
versioningit = "*"

[feature.developer.tasks]
test = "PYTHONPATH=src python -m unittest discover -s tests -t ."
test-unit = "PYTHONPATH=src python -m unittest discover -s tests/unit -t ."
test-system = "PYTHONPATH=src python -m unittest discover -s tests/system -t ."
test-analysis-unit = "PYTHONPATH=src python -m unittest discover -s tests/unit/analysis -t ."
test-analysis-system = "PYTHONPATH=src python -m unittest discover -s tests/system/analysis -t ."
test-calibration-unit = "PYTHONPATH=src python -m unittest discover -s tests/unit/calibration -t ."
test-calibration-system = "PYTHONPATH=src python -m unittest discover -s tests/system/calibration -t ."
test-unit-coverage = "PYTHONPATH=src coverage run -m unittest discover -s tests/unit -t . && coverage report"
default-analysis-inputs = "PYTHONPATH=src python src/mvesuvio/config/analysis_inputs.py"
lint = "ruff check src tests"
format = "ruff format src tests"
dev = "pip install -e ."

[feature.pypi-builder.tasks]
build-pypi = "python -m build"

[feature.conda-builder.tasks]
build-conda = "cd conda && conda mambabuild --croot /tmp/conda-bld ."

# Only used for building in CI on linux
[feature.conda-builder]
platforms = ["linux-64"]

# Only used for building in CI on linux
[feature.pypi-builder]
platforms = ["linux-64"]

[environments]
vesuvio-developer = ["mvesuvio", "developer"]
conda-builder = ["conda-builder"]
pypi-builder = ["pypi-builder"]




