name: Build and upload pypi package

inputs:
  token:
    description: 'PyPI API Token'
    required: true

description: Build and upload pypi package
runs:
  using: "composite"

  steps:
  - uses: prefix-dev/setup-pixi@v0
    with:
      pixi-version: v0.20.0
  - name: Build package
    shell: bash -l {0}
    run: pixi run build-pypi
  - name: Upload to PyPI
    shell: bash -l {0}
    env:
      TWINE_PASSWORD: ${{ inputs.token }}
    run: pixi run twine upload -u __token__ -p $TWINE_PASSWORD dist/*
