name: Build and upload pypi package

inputs:
  token:
    description: 'PyPI API Token'
    required: true

description: Build and upload pypi package
runs:
  using: "composite"

  steps:
  - name: Build package
    shell: bash
    run: pixi run build-pypi
  - name: Upload to PyPI
    shell: bash
    env:
      TWINE_PASSWORD: ${{ inputs.token }}
    run: pixi run twine upload -u __token__ -p $TWINE_PASSWORD dist/*
