name: Build and upload conda package

inputs:
  repository:
    description: 'Anaconda repository'
    required: true
    default: 'mantid'
  label:
    description: 'Label'
    required: false
    default: 'nightly'
  token:
    description: 'Anaconda API Token'
    required: true

description: Build and upload conda package
runs:
  using: "composite"

  steps:
  - name: Make build-env
    shell: bash -l {0}
    run: |
      conda clean --all --yes --quiet
      conda config --set always_yes yes --set changeps1 no
      conda create -n build-env
      conda activate build-env
      mamba install -c conda-forge mamba conda-build anaconda-client conda-verify boa
      conda config --set solver libmamba
      conda config --add channels conda-forge
      conda config --add channels mantid
      conda config --add channels mantid/label/nightly
      mamba install -c conda-forge 'poco >=1.14.2,<1.14.3'   # Needed for fix, attempt to remove at a later date

  - name: Build package
    shell: bash -l {0}
    run: |
      conda activate build-env
      conda clean --tempfiles --yes --quiet
      conda config --set anaconda_upload yes
      conda mambabuild --user ${{ inputs.repository }} --token ${{ inputs.token }} --label ${{ inputs.label }} $GITHUB_WORKSPACE/conda
