  {% set version_tag = environ.get('GIT_DESCRIBE_TAG', '0.0') %}
  {% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}
  {% set version_number = '.dev' + version_number if version_number != '0' else '' %}

  {% set version = version_tag + version_number %}

package:
  name: mvesuvio
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  script: versioningit && python -m pip install --ignore-installed .
  entry_points:
    - mvesuvio = mvesuvio.main:main

requirements:
  build:
    - python {{ python }}
    - setuptools
    - versioningit

  run:
    - python {{ python }}
    - mantid
    - matplotlib
    - iminuit
    - jacobi
    - dill

test:
  imports:
    - mvesuvio
  requires:
    - pytest
    - mock 
  source_files:
    - tests/unit/
    - tests/data/analysis/inputs/system_test_inputs.py      # Not a test, used by log file unit test
    - tests/data/analysis/unit/                             # Data used by several unit tests
    - src/mvesuvio/config/analysis_inputs.py                # Used to run basic mvesuvio run
    - src/mvesuvio/config/analysis_inputs/input_workspaces  # Inputs needed to run mvesuvio
    - tools/
  commands:
    - pytest
    - mvesuvio version
    - python src/mvesuvio/config/analysis_inputs.py

about:
  home: https://github.com/mantidproject/vesuvio
  license: GPL-3.0-or-later
  summary: Vesuvio is an instrument that performs Neuton Compton Scattering, based at ISIS, RAL, UK. This code processes raw output data to determine
           nuclear kinetic energies and moment distributions.
