  {% set version_tag = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
  {% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}
  {% set version_number = '_' + version_number if version_number != '0' else '' %}

  {% set version = version_tag + version_number %}

package:
  name: mvesuvio
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: python
  script: python -m pip install --ignore-installed .
  entry_points:
    - mvesuvio = mvesuvio.main:main

requirements:
  build:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - mantid
    - matplotlib
    - iminuit
    - jacobi {{ jacobi }}
    - dill

test:
  imports:
    - mvesuvio
  requires:
    - pytest
    - mock 
  source_files:
    - tests/unit/
    - tools/
  commands:
    - pytest
    - mvesuvio config    

about:
  home: https://github.com/mantidproject/vesuvio
  license: GPL-3.0-or-later
  summary: Vesuvio is an instrument that performs Neuton Compton Scattering, based at ISIS, RAL, UK. This code processes raw output data to determine
           nuclear kinetic energies and moment distributions.
