name: 'Run mvesuvio tests'
description: 'Runs unit and system tests for mvesuvio with coverage reporting'

inputs:
  token:
    description: 'Coveralls API Token'
    required: true

runs:
  using: 'composite'
  steps:
    # Set up pixi environment
    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0

    - name: Install mvesuvio package
      run: pixi run dev
      shell: bash

    - name: Run default analysis inputs
      run: pixi run default-analysis-inputs
      shell: bash

    - name: Run mvesuvio unit tests
      run: |
        pixi run test-unit-coverage
      shell: bash

    - name: Send coverage report to Coveralls
      if: runner.os != 'Windows'
      env:
        COVERALLS_REPO_TOKEN : ${{ inputs.token }}
      run: |
        pixi run -e vesuvio-development coveralls --service=github-actions
      shell: bash

    - name: Run mvesuvio system tests
      run: |
        pixi run test-system
      shell: bash
