name: mvesuvio nightly build

on: push
# on:
#   schedule:
#     - cron: '0 2 * * *'

jobs:
  test:
    runs-on: ubuntu-latest 
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout mvesuvio
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          activate-environment: mvesuvio-env
          environment-file: environment.yml
          auto-activate-base: false

      - name: Install mvesuvio package
        # The editable flag is necessary for coverage to find the src/ files
        run: pip install -e .

      # Runs Unit tests
      - name: Run mvesuvio analysis unit tests
        run: |
          coverage run -m unittest discover -s ./tests/unit
          coverage report

      # Send coverage report to Coveralls
      - name: Send coverage report to Coveralls
        env:
          COVERALLS_REPO_TOKEN : ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          coveralls --service=github-actions

      # # Runs System tests
      # - name: Run mvesuvio analysis system tests
      #   run: |
      #     python -m unittest discover -s ./tests/system
