name: mvesuvio pull request workflow

on: push

jobs:
  test:
    runs-on: self-hosted 
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      # Set up conda environnment
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          activate-environment: vesuvio-env
          environment-file: environment.yml
          auto-activate-base: false

      - name: Flake8
        run: python -m flake8 --config=config.flake8

      - name: Install Git 
        run: pip install git

      # Remove `export MANTIDPROPERTIES=$(pwd)/Mantid.user.properties` when updated to mantid > 6.8.0
      - name: Install mvesuvio package
        run: pip install .

      - name: Check for analysis files changed 
        run: |
          echo "analysis-changed=$(git diff --name-only ${{ github.sha }} ${{ github.event.before }} | grep -q '^src/' && echo true || echo false)" >> $GITHUB_ENV

      - name: Check for calibration files changed 
        run: |
          echo "calibration-changed=$(git diff --name-only ${{ github.sha }} ${{ github.event.before }} | grep -q '^tools/calibration_scripts/' && echo true || echo false)" >> $GITHUB_ENV

      # Runs Unit tests
      - name: Run mvesuvio Analysis Unit Tests
        if: ${{ env.analysis-changed == 'true'}}
        run: |
          export MANTIDPROPERTIES=$(pwd)/Mantid.user.properties
          python -m unittest discover -s ./tests/analysis/unit

      # Runs System tests
      - name: Run mvesuvio Analysis System Tests
        if: ${{ env.analysis-changed == 'true'}}
        run: |
          python -m unittest discover -s ./tests/analysis/system

      - name: Run mvesuvio Calibration Unit Tests
        if: ${{ env.calibration-changed == 'true'}}
        run: |
          export MANTIDPROPERTIES=$(pwd)/Mantid.user.properties
          python -m unittest discover -s ./tests/calibration/unit

      - name: Run Vesuvio Calibration System Tests
        if: ${{ env.calibration-changed == 'true'}}
        run: |
          python -m unittest discover -s ./tests/calibration/system

      # Report coverage
      #- name: Report Coverage
      #  run: coverage report
