name: Vesuvio pull request workflow

# Controls when the workflow will run
on:
  # By default runs on opened, synchronize (push) and reopened
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-18.04
    defaults:
      run:
        #run in bash rather than sh
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repo to comp that runs action (as opposed to v3, under $GITHUB_WORKSPACE)
      - uses: actions/checkout@v2
        with:
          # Fetch entire history for all branches and tags
          fetch_depth: 0

      # Set up conda environnment
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          activate-environment: vesuvio-env
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false

      # Runs flake8
      - name: Flake8
        run: python -m flake8 --config=config.flake8

      # Runs tests
      - name: unittests
        run: coverage run -m unittest discover -s ./vesuvio_analysis

      # Runs system tests
      - name: systemtests
        run: python run system_tests/test_runner.py

      # Report coverage
      - name: coverage
        run: coverage report