name: Run tests on PR

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up pixi environment
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0

      - name: Check for analysis files changed 
        run: |
          echo "analysis-changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q -e '^src/' -e '^tests/' && echo true || echo false)" >> $GITHUB_ENV

      - name: Check for calibration files changed 
        run: |
          echo "calibration-changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q -e '^tools/calibration_scripts/' -e '^tests/' && echo true || echo false)" >> $GITHUB_ENV

      - name: Check if first workflow to run on PR 
        run: |
          # Check if the base commit (before the PR) exists in the history
          if ! git merge-base --is-ancestor ${{ github.event.pull_request.base.sha }} HEAD; then
            echo "First push detected (or force push), running all tests."
            echo "analysis-changed=true" >> $GITHUB_ENV
            echo "calibration-changed=true" >> $GITHUB_ENV
          fi

      - name: Run mvesuvio Analysis Unit Tests
        if: ${{ env.analysis-changed == 'true'}}
        run: |
          pixi run -e vesuvio-developer test-analysis-unit

      - name: Run mvesuvio Analysis System Tests
        if: ${{ env.analysis-changed == 'true'}}
        run: |
          pixi run -e vesuvio-developer test-analysis-system

      - name: Run mvesuvio Calibration Unit Tests
        if: ${{ env.calibration-changed == 'true'}}
        run: |
          pixi run -e vesuvio-developer test-calibration-unit

      - name: Run Vesuvio Calibration System Tests
        if: ${{ env.calibration-changed == 'true'}}
        run: |
          pixi run -e vesuvio-developer test-calibration-system
